### ISSUE TITLE
Goals for December koya

### ISSUE THREAD

**Issue by watsonso** [mizuhiki-team/TIL#238]
## Reading
- [x] エンジニアのためのマネジメントキャリアパス
- [ ] プロダクトマネジメント
- [ ] 実践ハイパフォーマンスMySQL
- [ ] データ指向アプリケーションデザイン
- [ ] データサイエンスのための統計学入門
- [ ] 「原因と結果」の経済学

### web
- **Web APIの設計**
  - [ ] [Web APIの設計 Vol.1](https://github.com/the-cyber/TIL/issues/159) note **🥉 sprint31**
  - [ ] [Web APIの設計 Vol.2](https://github.com/the-cyber/TIL/issues/247) note **🚀  sprint32**
  - [ ] [Web APIの設計 Vol.3](https://github.com/the-cyber/TIL/issues/248) note **🎁  sprint33**

### data platform
- **10年戦えるデータ分析入門 SQLを武器にデータ活用時代を生き抜く**
  - [x] [10年戦えるデータ分析入門　SQLを武器にデータ活用時代を生き抜く Vol.1](https://github.com/mizuhiki-team/TIL/issues/176) **[note](https://note.com/watson0360/n/n86a85e7b6de5)** **👍 sprint29**
  - [x] [10年戦えるデータ分析入門　SQLを武器にデータ活用時代を生き抜く Vol.2](https://github.com/mizuhiki-team/TIL/issues/242) **[note](https://note.com/watson0360/n/nf8940b185043)** **🥇 sprint30**
  - [x] [10年戦えるデータ分析入門　SQLを武器にデータ活用時代を生き抜く Vol.3](https://github.com/mizuhiki-team/TIL/issues/243) **[note](https://note.com/watson0360/n/n6b1fabd934f4)** **🥉 sprint31**
  - [ ] [10年戦えるデータ分析入門　SQLを武器にデータ活用時代を生き抜く Vol.4](https://github.com/mizuhiki-team/TIL/issues/244) note **🚀  sprint32**

### marketing
- **徹底活用 Google アナリティクス**
  - [ ]  [徹底活用 Google アナリティクス Vol.1](https://github.com/mizuhiki-team/TIL/issues/219) note **🥉 sprint31**
  - [ ]  [徹底活用 Google アナリティクス Vol.2](https://github.com/mizuhiki-team/TIL/issues/249) note **🚀  sprint32**
  - [ ]  [徹底活用 Google アナリティクス Vol.3](https://github.com/mizuhiki-team/TIL/issues/250) note **🎁  sprint33**

### infra 
- **Google Cloud Platform GAEソフトウェア開発入門**
  - [x] [Google Cloud Platform GAEソフトウェア開発入門 Vol.1](https://github.com/mizuhiki-team/TIL/issues/169) **[note](https://note.com/watson0360/n/n02826c561162)** **👍 sprint29**
  - [ ] [Google Cloud Platform GAEソフトウェア開発入門 Vol.2](https://github.com/mizuhiki-team/TIL/issues/245) note **🥉 sprint31**
  - [ ] [Google Cloud Platform GAEソフトウェア開発入門 Vol.3](https://github.com/mizuhiki-team/TIL/issues/246) note **🚀  sprint32**

## 12月の終わりまでにどうなっていれば良いか？
- [ ] ソリューションアーキテクト - プロフェッショナルの取得
  - https://aws.amazon.com/jp/certification/certified-solutions-architect-professional/
- [ ] Daily DairyのAndroidアプリの基盤が出来ている
- [ ] Daily Dairyのインフラの基盤が出来ている
- [ ] GAの使い方を一通り理解しサービスに反映が出来ている
- [ ] kaminashiとmiruhoの給料あげる
