### ISSUE TITLE
1.4-1.10　ToDo

### ISSUE THREAD

**Issue by nr-ryotaro** [mizuhiki-team/TIL#321]
仕事
- [ ] 401K確定拠出型年金　掛け金変更
- [x] 本番リリース立ち合い
- [ ] 論文作成20Pまで進める
- [x] スライド10P作成

生活
- [x] ふるさと納税書類送付
- [x] ついでにやりかたNoteに書く
- [x] ドラム机2021Verデザイン構築
- [x] ドラムテレビ棚2021Verデザインラフ書く

デザイン
- [x] 2021.2月Photoデザイン色調補正
- [x] Illust　Ver下書き・ラフ作成
- [x] 姉ロゴ作成　リボン部分は松尾に相談

小説
- [x] しゅんと大臣のおすすめ待ち

Beatles和訳
- [x] I saw her standing there
- [x] Misery
- [x] Annna

筋トレ
- [x] 10Minsサイクル腹筋
- [x] 2mins腕立て×２
- [x] 3mins背筋×2

Run
- [x] １
- [x] ２

スタジオ
- [x] １

Note
- [x] Beatles
- [x] 映画　ぷぺる
- [x] クリスマス・おせち料理

ディぐる案件
- [x] Hackintosh
- [x] Bessa R2
- [x] Vogither LENTAR 50mmレンズ
- [x] M1 mac mini or mac book pro

英語
スタサプ
- [x] 10ｈ
- [x] 12ｈ
TOEIC
- [x] 1
- [x] 2
